index:
    path: /
    controller: App\Controller\BasicController::index

advisor_create:
    path: /api/v1/advisor
    methods: POST
    controller: App\Controller\AdvisorController:create

advisors_get:
    path: /api/v1/advisor
    methods: GET
    controller: App\Controller\AdvisorController:getAdvisor

advisor_delete:
    path: /api/v1/advisor/{id}
    methods: DELETE
    controller: App\Controller\AdvisorController:delete

advisor_update:
    path: /api/v1/advisor/{id}
    methods: PATCH
    controller: App\Controller\AdvisorController:update

advisor_get:
    path: /api/v1/advisor/{id}
    methods: GET
    controller: App\Controller\AdvisorController:getAdvisor

swagger_doc:
    path: /api/v1/doc
    methods: GET
    controller: App\Controller\BasicController::getSwaggerDoc