parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\ArgumentResolver\CreateAdvisorResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
    App\ArgumentResolver\UpdateAdvisorResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }