App\DTO\EquipmentDemandRequestDTO:
  properties:
    date:
      - NotNull: ~
    station:
      - NotNull: ~
    page:
      - PositiveOrZero:
          message: "You should provide valid page (0 or greater)"
    limit:
      - PositiveOrZero:
          message: "You should provide valid page (0 or greater)"
      - LessThanOrEqual:
          value: 20
          message: "You should provide less than 20"