App\DTO\EquipmentDemandRequestDTO:
  properties:
    startDate:
      - NotNull: ~
    endDate:
      - NotNull: ~
    station:
      - NotNull: ~
    page:
      - PositiveOrZero: ~
    limit:
      - PositiveOrZero: ~
      - LessThanOrEqual: 20